# -*- coding: utf-8 -*-
"""AluraStoreLatam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNVj32O5ap2PHP5jHqiDhyjUDokosioz

### Importación de datos
"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

tienda2.head()

tienda3.head()

tienda4.head()

"""#1. Análisis de facturación


"""

import matplotlib.pyplot as plt

# calcular facturación
facturacion_t1 = tienda['Precio'].sum()
facturacion_t2 = tienda2['Precio'].sum()
facturacion_t3 = tienda3['Precio'].sum()
facturacion_t4 = tienda4['Precio'].sum()

facturacion = [facturacion_t1, facturacion_t2, facturacion_t3, facturacion_t4]

# Calcular la cantidad total de productos vendidos por tienda
cantidad_t1 = tienda.shape[0]
cantidad_t2 = tienda2.shape[0]
cantidad_t3 = tienda3.shape[0]
cantidad_t4 = tienda4.shape[0]

cantidad_total_vendida = [cantidad_t1, cantidad_t2, cantidad_t3, cantidad_t4]

# Crear un DataFrame para facilitar la graficación
df_cantidad_vendida = pd.DataFrame({
    'Tienda': nombres_tiendas,
    'Cantidad de Productos Vendidos': cantidad_total_vendida
})

plt.figure(figsize=(8,5))
sns.barplot(x='Tienda', y='Cantidad de Productos Vendidos', data=df_cantidad_vendida, palette='GnBu_d')

plt.title('Cantidad Total de Productos Vendidos por Tienda')
plt.xlabel('Tiendas')
plt.ylabel('Cantidad de Productos Vendidos')

# Añadir etiquetas de valor a las barras
for index, row in df_cantidad_vendida.iterrows():
    plt.text(index, row['Cantidad de Productos Vendidos'] + 10, int(row['Cantidad de Productos Vendidos']), color='black')

plt.show()

nombres_tiendas = ['Tienda 1','Tienda 2','Tienda 3','Tienda 4']

plt.figure(figsize=(8,5))
plt.bar(nombres_tiendas, facturacion)

plt.title("Facturación total por tienda")
plt.xlabel("Tiendas")
plt.ylabel("Ingresos")

plt.show()

"""# 2. Ventas por categoría"""

top_3_categorias_por_tienda = []

for i, categoria_series in enumerate([categoria_t1, categoria_t2, categoria_t3, categoria_t4]):
    tienda_nombre = nombres_tiendas[i]
    top_3 = categoria_series.head(3)
    for categoria, ventas in top_3.items():
        top_3_categorias_por_tienda.append({'Tienda': tienda_nombre, 'Categoría': categoria, 'Ventas': ventas})

df_top_3_categorias = pd.DataFrame(top_3_categorias_por_tienda)

plt.figure(figsize=(12, 7))
sns.barplot(x='Tienda', y='Ventas', hue='Categoría', data=df_top_3_categorias, palette='viridis')
plt.title('Top 3 Categorías Más Vendidas por Tienda')
plt.xlabel('Tienda')
plt.ylabel('Cantidad de Ventas')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Categoría del Producto', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""### Cantidad de productos vendidos por categoría en Tienda 1"""

display(categoria_t1)

"""### Cantidad de productos vendidos por categoría en Tienda 2"""

display(categoria_t2)

"""### Cantidad de productos vendidos por categoría en Tienda 3"""

display(categoria_t3)

"""### Cantidad de productos vendidos por categoría en Tienda 4"""

display(categoria_t4)

"""# 3. Calificación promedio de la tienda

"""

calificacion_t1 = tienda['Calificación'].mean()
calificacion_t2 = tienda2['Calificación'].mean()
calificacion_t3 = tienda3['Calificación'].mean()
calificacion_t4 = tienda4['Calificación'].mean()

promedio_calificaciones = [
    calificacion_t1,
    calificacion_t2,
    calificacion_t3,
    calificacion_t4
]

promedio_calificaciones_df = pd.DataFrame({
    'Tienda': nombres_tiendas,
    'Calificación Promedio': promedio_calificaciones
})

display(promedio_calificaciones_df)

plt.figure(figsize=(8, 5))
sns.barplot(x='Tienda', y='Calificación Promedio', data=promedio_calificaciones_df, palette='viridis')
plt.title('Calificación Promedio por Tienda')
plt.xlabel('Tienda')
plt.ylabel('Calificación Promedio')
plt.ylim(0, 5) # Las calificaciones suelen ir de 1 a 5

# Añadir etiquetas de valor a las barras
for index, row in promedio_calificaciones_df.iterrows():
    plt.text(index, row['Calificación Promedio'] + 0.05, round(row['Calificación Promedio'], 2), color='black', ha="center")

plt.show()

"""# 4. Productos más y menos vendidos"""

df_total = pd.concat([tienda, tienda2, tienda3, tienda4], ignore_index=True)

productos_vendidos = df_total['Producto'].value_counts()

producto_mas_vendido = productos_vendidos.index[0]
cantidad_mas_vendido = productos_vendidos.iloc[0]

producto_menos_vendido = productos_vendidos.index[-1]
cantidad_menos_vendido = productos_vendidos.iloc[-1]

print(f"Producto más vendido: {producto_mas_vendido} (Cantidad: {cantidad_mas_vendido})")
print(f"Producto menos vendido: {producto_menos_vendido} (Cantidad: {cantidad_menos_vendido})")

plt.figure(figsize=(12, 6))
productos_vendidos.head(10).plot(kind='bar', color='skyblue')
plt.title('Top 10 Productos Más Vendidos (Todas las Tiendas)')
plt.xlabel('Producto')
plt.ylabel('Cantidad Vendida')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))
productos_vendidos.tail(10).plot(kind='bar', color='salmon')
plt.title('Top 10 Productos Menos Vendidos (Todas las Tiendas)')
plt.xlabel('Producto')
plt.ylabel('Cantidad Vendida')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""# 5. Envío promedio por tienda"""

envio_promedio_t1 = tienda['Costo de envío'].mean()
envio_promedio_t2 = tienda2['Costo de envío'].mean()
envio_promedio_t3 = tienda3['Costo de envío'].mean()
envio_promedio_t4 = tienda4['Costo de envío'].mean()

promedio_envios = [
    envio_promedio_t1,
    envio_promedio_t2,
    envio_promedio_t3,
    envio_promedio_t4
]

promedio_envios_df = pd.DataFrame({
    'Tienda': nombres_tiendas,
    'Costo de Envío Promedio': promedio_envios
})

display(promedio_envios_df)

plt.figure(figsize=(8, 5))
sns.barplot(x='Tienda', y='Costo de Envío Promedio', data=promedio_envios_df, palette='magma')
plt.title('Costo de Envío Promedio por Tienda')
plt.xlabel('Tienda')
plt.ylabel('Costo de Envío Promedio')

# Añadir etiquetas de valor a las barras
for index, row in promedio_envios_df.iterrows():
    plt.text(index, row['Costo de Envío Promedio'] + 500, f"{row['Costo de Envío Promedio']:.2f}", color='black', ha="center")

plt.tight_layout()
plt.show()

"""## Informe Final: Evaluación de Desempeño de Tiendas

### Introducción

El presente análisis tiene como objetivo evaluar el desempeño de las cuatro tiendas, con el fin de recomendar al Sr. Juan cuál de ellas debería vender para invertir en un nuevo emprendimiento.

Para realizar esta evaluación se analizaron diferentes indicadores clave del rendimiento comercial de cada tienda, incluyendo:

- Los ingresos totales generados por cada tienda.

- Las categorías de productos más y menos vendidas.

- Las calificaciones promedio otorgadas por los clientes.

- Los productos más y menos vendidos.

- El costo promedio de envío.

A partir de estos indicadores se generaron visualizaciones y análisis comparativos que permiten identificar fortalezas y debilidades en cada tienda.

### Desarrollo del Análisis

#### 1. Ingresos Totales (Facturación)

El análisis de facturación reveló las siguientes cifras:

- Tienda 1: $1,150,880,400
- Tienda 2: $1,116,343,500
- Tienda 3: $1,098,019,600
- Tienda 4: $1,038,375,700

La Tienda 1 genera los mayores ingresos, mientras que la Tienda 4 tiene la facturación más baja. Sin embargo, en términos de cantidad de productos vendidos, todas las tiendas muestran volúmenes muy similares (aproximadamente 2359 productos cada una), lo que sugiere que la diferencia en facturación podría deberse a los precios de los productos vendidos.

#### 2. Ventas por Categoría

Al analizar las categorías de productos, se encontró que:

 En todas las tiendas,'Muebles' y 'Electrónicos' son consistentemente las dos categorías con mayores ventas.
 La tercera categoría más vendida a menudo es'Juguetes', con algunas variaciones entre tiendas. El gráfico "Top 3 Categorías Más Vendidas por Tienda" ilustra claramente esta distribución.

#### 3. Calificaciones Promedio de los Clientes

Las calificaciones promedio de los clientes por tienda son:

- Tienda 1: 3.98
- Tienda 2: 4.04
- Tienda 3: 4.05
- Tienda 4: 4.00

La Tienda 3 destaca ligeramente con la calificación promedio más alta, lo que indica un alto nivel de satisfacción del cliente.

#### 4. Productos Más y Menos Vendidos (General)

Considerando todas las tiendas en conjunto:

  El producto más vendido es "Mesa de noche" (210 unidades).
  El producto menos vendido es "Celular ABXY" (157 unidades).

Los gráficos de barras "Top 10 Productos Más Vendidos" y "Top 10 Productos Menos Vendidos" ofrecen una visión detallada de esta tendencia.

#### 5. Costo de Envío Promedio

Los costos de envío promedio por tienda son:

- Tienda 1: $26,018.61
- Tienda 2: $25,216.24
- Tienda 3: $24,805.68
- Tienda 4: $23,459.46

La Tienda 4 tiene el costo de envío promedio más bajo, lo cual es una ventaja operativa, mientras que la Tienda 1 registra el más alto.

### Conclusión y Recomendación

Para el Sr. Juan, que busca vender una tienda para invertir en un nuevo emprendimiento, la decisión debe basarse en identificar la tienda con el menor rendimiento financiero o la que ofrece el menor potencial de crecimiento en su estado actual, liberando así capital de una manera estratégica.

Considerando todos los factores:

-   La Tienda 1 tiene la facturación más alta, lo que la convierte en el activo más fuerte en términos de ingresos directos, a pesar de tener el costo de envío más alto y la calificación promedio más baja (aunque todavía buena).
-   La Tienda 3 se distingue por tener la calificación promedio más alta, lo que indica una excelente reputación entre los clientes, a pesar de tener la segunda facturación más baja y costos de envío moderados.
-   La Tienda 2 presenta un desempeño intermedio en todas las métricas, sin sobresalir ni mostrar debilidades significativas.
-   La Tienda 4 consistentemente muestra la menor facturación total ($1,038,375,700). Aunque tiene el costo de envío promedio más bajo, sus bajos ingresos, en comparación con un volumen de ventas similar al de otras tiendas, sugieren que podría estar vendiendo productos de menor valor o con márgenes de beneficio reducidos. Su calificación promedio es buena, pero no la más alta.

**Recomendación:**

Se recomienda al Sr. Juan vender la Tienda 4.

**Justificación:**

La Tienda 4 es la que presenta la facturación total más baja. Aunque posee el menor costo de envío promedio, su contribución global a los ingresos de la cadena es la más reducida. Al vender la Tienda 4, el Sr. Juan estaría desinvirtiendo en el activo con el menor rendimiento financiero actual, lo que le permitiría liberar la mayor cantidad de capital para su nuevo emprendimiento con el menor impacto en los ingresos totales del resto de la cadena de tiendas. Las otras tiendas, especialmente la Tienda 1 (por sus ingresos) y la Tienda 3 (por la satisfacción del cliente), muestran un valor más estratégico para mantener en el portafolio actual.
"""

!pip install folium

import folium
from folium.plugins import HeatMap
import pandas as pd
import matplotlib.pyplot as plt

mapa_heat_t1 = folium.Map(location=[centro_lat, centro_lon], zoom_start=5)

heat_data_t1 = [
    [row['lat'], row['lon'], row['Precio']]
    for _, row in tienda.iterrows()
]

HeatMap(heat_data_t1).add_to(mapa_heat_t1)

mapa_heat_t1

mapa_heat_t2 = folium.Map(location=[centro_lat, centro_lon], zoom_start=5)

heat_data_t2 = [
    [row['lat'], row['lon'], row['Precio']]
    for _, row in tienda2.iterrows()
]

HeatMap(heat_data_t2).add_to(mapa_heat_t2)

mapa_heat_t2

mapa_heat_t3 = folium.Map(location=[centro_lat, centro_lon], zoom_start=5)

heat_data_t3 = [
    [row['lat'], row['lon'], row['Precio']]
    for _, row in tienda3.iterrows()
]

HeatMap(heat_data_t3).add_to(mapa_heat_t3)

mapa_heat_t3

mapa_heat_t4 = folium.Map(location=[centro_lat, centro_lon], zoom_start=5)

heat_data_t4 = [
    [row['lat'], row['lon'], row['Precio']]
    for _, row in tienda4.iterrows()
]

HeatMap(heat_data_t4).add_to(mapa_heat_t4)

mapa_heat_t4

df_all_stores = pd.concat([tienda, tienda2, tienda3, tienda4], ignore_index=True)

centro_lat = df_all_stores['lat'].mean()
centro_lon = df_all_stores['lon'].mean()

print(f"Central Latitude: {centro_lat}")
print(f"Central Longitude: {centro_lon}")

import folium
from folium.plugins import HeatMap
from folium.features import FeatureGroup

# Initialize the base map centered at the overall average coordinates
combined_map = folium.Map(location=[centro_lat, centro_lon], zoom_start=5)

# List of stores and their names for iteration
stores = [tienda, tienda2, tienda3, tienda4]
store_names = ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4']

# Iterate through each store to create and add its heatmap as a FeatureGroup
for i, store_df in enumerate(stores):
    store_name = store_names[i]

    # Prepare heat data for the current store
    heat_data = [
        [row['lat'], row['lon'], row['Precio']]
        for _, row in store_df.iterrows()
    ]

    # Create a FeatureGroup for the current store's heatmap
    fg = FeatureGroup(name=f'{store_name} Heatmap')

    # Add the HeatMap to the FeatureGroup
    HeatMap(heat_data).add_to(fg)

    # Add the FeatureGroup to the combined map
    fg.add_to(combined_map)

# Add a LayerControl to the map to enable toggling heatmaps
folium.LayerControl().add_to(combined_map)

# Display the combined map
combined_map

"""Las cuatro tiendas presentan un patrón geográfico similar, con una fuerte concentración de ventas en Bogotá y Medellín. Sin embargo, también muestran presencia en otras ciudades: Tienda 1 y Tienda 2 tienen algunas ventas adicionales en lugares como Cali y Cartagena; Tienda 3 destaca por una mayor presencia en ciudades costeras como Santa Marta y Barranquilla; y Tienda 4 muestra actividad específica en ciudades como Cúcuta y Pereira, lo que sugiere posibles éxitos regionales o estrategias de marketing enfocadas en esas zonas.

"""